# Run `npx nyc --help` or visit [1]
#
# [1]: https://github.com/istanbuljs/nyc?tab=readme-ov-file#common-configuration-options

# Recommended setup by [1]. The rest of this file defines overrides.
#
# [1]: https://github.com/istanbuljs/nyc?tab=readme-ov-file#typescript-projects
extends: "@istanbuljs/nyc-config-typescript"

# Instrument all files, not just the ones touched by the test suite.
all: true

# By default, nyc only attempts to handle JS.
extension:
- ts

include:
- src/**/*.ts     # Contains all app-relevant code.
exclude:
- src/public/     # Uses web-test-runner's coverage tool
