/**
 * @description This file is used by `sequelize-cli` to generate database
 * migrations [1]. It is adapted from the one autogenerated by `sequelize-cli`.
 * 
 * [1]: https://sequelize.org/master/manual/migrations.html
 */

import { Sequelize } from "sequelize";

import * as DBModels from "./DBModels";
import { DATABASE_URI } from "../../config";

let sequelize = new Sequelize(DATABASE_URI);
const db: { [s: string]: any } = {};

Object.values(DBModels).forEach((val) => {
    // Database models get exported as functions. I don't know of a better
    // filter. Ideally, `x.tableName` is defined iff `x` is a sequelize model.
    if (typeof val === "function" && val.tableName) {
        db[val.name] = val;
    }
});

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

console.log(`[Migrations] Here are the DB exports: ${Object.keys(db)}`);

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
